In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import warnings
import pandas as pd
DATA=pd.read_csv(r"DATA.csv")
DATA

,#EventID,Time,Latitude,Longitude,Depth/Km,Author,Catalog,Contributor,ContributorID,MagType,Magnitude,MagAuthor,EventLocationName
0,79,1985-01-02 23:26:09.581820,41.7150,13.9410,5.8,BULLETIN-VAX,NaN,NaN,NaN,Md,2.6,--,6 km S Civitella Alfedena (AQ)
1,89,1985-01-03 01:14:43.481820,41.6770,13.9310,6.1,BULLETIN-VAX,NaN,NaN,NaN,Md,2.5,--,6 km NE Picinisco (FR)
2,199,1985-01-04 17:26:06.731820,46.1580,7.1740,10.0,BULLETIN-VAX,NaN,NaN,NaN,M,3.8,--,Confine Italia-Svizzera (SVIZZERA)
3,229,1985-01-05 00:28:21.311820,45.3380,6.6410,5.0,BULLETIN-VAX,NaN,NaN,NaN,M,3.7,--,Confine Italia-Francia (FRANCIA)
4,239,1985-01-05 04:15:30.131820,45.4090,6.6270,10.0,BULLETIN-VAX,NaN,NaN,NaN,M,3.2,--,Confine Italia-Francia (FRANCIA)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181772,24334191,2020-04-29 11:45:50.661820,45.9167,12.1917,10.1,SURVEY-INGV,NaN,NaN,NaN,ML,1.7,--,2 km SW Refrontolo (TV)
181773,24335541,2020-04-29 14:43:14.461820,38.4090,13.5617,28.2,SURVEY-INGV,NaN,NaN,NaN,ML,2.3,--,Costa Siciliana centro-settentrionale (Palermo)
181774,24336421,2020-04-29 16:52:06.501820,42.8882,13.0363,10.0,SURVEY-INGV,NaN,NaN,NaN,ML,1.8,--,1 km N Preci (PG)
181775,24336481,2020-04-29 16:58:41.341820,37.7683,14.6293,38.0,SURVEY-INGV,NaN,NaN,NaN,ML,2.2,--,3 km SE Troina (EN)
181776,24337031,2020-04-29 19:49:26.781820,37.8797,12.9638,10.0,SURVEY-INGV,NaN,NaN,NaN,ML,1.6,--,10 km E Calatafimi-Segesta (TP)

In [4]:
DATA.describe()

,#EventID,Latitude,Longitude,Depth/Km,Catalog,Contributor,ContributorID,Magnitude
count,1.817770e+05,181777.000000,181777.000000,181777.000000,0.0,0.0,0.0,181777.000000
mean,5.871837e+06,42.212456,13.195668,14.416735,NaN,NaN,NaN,2.082843
std,6.383951e+06,2.098700,1.881832,25.956156,NaN,NaN,NaN,0.504350
min,7.900000e+01,36.100000,6.300000,-0.300000,NaN,NaN,NaN,1.500000
25%,1.314169e+06,41.681000,12.750000,8.100000,NaN,NaN,NaN,1.700000
50%,2.286459e+06,42.776200,13.196200,10.000000,NaN,NaN,NaN,2.000000
75%,9.224341e+06,43.229200,14.218000,11.200000,NaN,NaN,NaN,2.400000
max,2.433703e+07,47.099800,18.400000,644.400000,NaN,NaN,NaN,6.500000

In [7]:
DATA.isna().sum()

#EventID                  0
Time                      0
Latitude                  0
Longitude                 0
Depth/Km                  0
Author                    0
Catalog              181777
Contributor          181777
ContributorID        181777
MagType                   0
Magnitude                 0
MagAuthor                 0
EventLocationName         0
dtype: int64

In [9]:
DATA.drop(['Catalog','Contributor','ContributorID'], axis=1,inplace=True )

In [12]:
DATA['MagAuthor'].value_counts()

--    181777
Name: MagAuthor, dtype: int64

In [13]:
DATA.drop(['MagAuthor'], axis=1,inplace=True )
DATA

,#EventID,Time,Latitude,Longitude,Depth/Km,Author,MagType,Magnitude,EventLocationName
0,79,1985-01-02 23:26:09.581820,41.7150,13.9410,5.8,BULLETIN-VAX,Md,2.6,6 km S Civitella Alfedena (AQ)
1,89,1985-01-03 01:14:43.481820,41.6770,13.9310,6.1,BULLETIN-VAX,Md,2.5,6 km NE Picinisco (FR)
2,199,1985-01-04 17:26:06.731820,46.1580,7.1740,10.0,BULLETIN-VAX,M,3.8,Confine Italia-Svizzera (SVIZZERA)
3,229,1985-01-05 00:28:21.311820,45.3380,6.6410,5.0,BULLETIN-VAX,M,3.7,Confine Italia-Francia (FRANCIA)
4,239,1985-01-05 04:15:30.131820,45.4090,6.6270,10.0,BULLETIN-VAX,M,3.2,Confine Italia-Francia (FRANCIA)
...,...,...,...,...,...,...,...,...,...
181772,24334191,2020-04-29 11:45:50.661820,45.9167,12.1917,10.1,SURVEY-INGV,ML,1.7,2 km SW Refrontolo (TV)
181773,24335541,2020-04-29 14:43:14.461820,38.4090,13.5617,28.2,SURVEY-INGV,ML,2.3,Costa Siciliana centro-settentrionale (Palermo)
181774,24336421,2020-04-29 16:52:06.501820,42.8882,13.0363,10.0,SURVEY-INGV,ML,1.8,1 km N Preci (PG)
181775,24336481,2020-04-29 16:58:41.341820,37.7683,14.6293,38.0,SURVEY-INGV,ML,2.2,3 km SE Troina (EN)
181776,24337031,2020-04-29 19:49:26.781820,37.8797,12.9638,10.0,SURVEY-INGV,ML,1.6,10 km E Calatafimi-Segesta (TP)

In [15]:
DATA.to_csv(r"C:\\Users\diego\OneDrive\Desktop\DS\kaggle_datasets\Italian_Catalogue.csv")